.TH "C:/Users/crist/OneDrive/Documentos/PlatformIO/Projects/LED_RGB/LED_RGB/data Directory Reference" 3 "Thu Jul 16 2020" "Version 1.0" "Aqua Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/crist/OneDrive/Documentos/PlatformIO/Projects/LED_RGB/LED_RGB/data Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBindex\&.htm\fP"
.br
.ti -1c
.RI "file \fBscp\&.js\fP"
.br
.ti -1c
.RI "file \fBst\&.css\fP"
.br
.in -1c
