.TH "Config" 3 "Thu Jul 16 2020" "Version 1.0" "Aqua Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config \- Struct for setting\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBuser\fP [20]"
.br
.ti -1c
.RI "char \fBpass\fP [16]"
.br
.ti -1c
.RI "char \fBhost\fP [20]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for setting\&. 

Generates struct for setting object
.PP
\fBSee also\fP
.RS 4
other classes
.IP "\(bu" 2
\fBserverA\fP
.IP "\(bu" 2
\fBhttpUpdater\fP
.IP "\(bu" 2
\fBRGB\fP 
.PP
.RE
.PP

.PP
Definition at line 144 of file main\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "char Config::host[20]"
hostname for local access 
.PP
Definition at line 147 of file main\&.cpp\&.
.SS "char Config::pass[16]"
paasword for access 
.PP
Definition at line 146 of file main\&.cpp\&.
.SS "char Config::user[20]"
username for login 
.PP
Definition at line 145 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aqua Control from the source code\&.
