.TH "httpUpdater" 3 "Thu Jul 16 2020" "Version 1.0" "Aqua Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httpUpdater \- Update class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Update class\&. 

provide update for firmware on the http request
.PP
\fBSee also\fP
.RS 4
other classes
.IP "\(bu" 2
\fBserverA\fP
.IP "\(bu" 2
\fBRGB\fP 
.PP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aqua Control from the source code\&.
