.TH "C:/Users/crist/OneDrive/Documentos/PlatformIO/Projects/LED_RGB/LED_RGB/data/index.htm" 3 "Thu Jul 16 2020" "Version 1.0" "Aqua Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/crist/OneDrive/Documentos/PlatformIO/Projects/LED_RGB/LED_RGB/data/index.htm
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Aqua Control from the source code\&.
