.TH "md__c_1__users_crist__one_drive__documentos__platform_i_o__projects__l_e_d__r_g_b__l_e_d__r_g_b__r_e_a_d_m_e" 3 "Thu Jul 16 2020" "Version 1.0" "Aqua Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users_crist__one_drive__documentos__platform_i_o__projects__l_e_d__r_g_b__l_e_d__r_g_b__r_e_a_d_m_e \- LED_RGB 

