.TH "RGB" 3 "Thu Jul 9 2020" "Version 1.0" "Aqua Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGB \- Struct for Led\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBr\fP"
.br
.RI "RECEIVE BYTE COLOR RED\&. "
.ti -1c
.RI "byte \fBg\fP"
.br
.RI "RECEIVE BYTE COLOR GREEN\&. "
.ti -1c
.RI "byte \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for Led\&. 

Generates struct for rgb color object
.PP
\fBSee also\fP
.RS 4
other classes
.IP "\(bu" 2
\fBserverA\fP
.IP "\(bu" 2
\fBhttpUpdater\fP 
.PP
.RE
.PP

.PP
Definition at line 113 of file main\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "byte RGB::b"
RECEIVE BYTE COLOR BLUE 
.PP
Definition at line 120 of file main\&.cpp\&.
.SS "byte RGB::g"

.PP
RECEIVE BYTE COLOR GREEN\&. 
.PP
Definition at line 118 of file main\&.cpp\&.
.SS "byte RGB::r"

.PP
RECEIVE BYTE COLOR RED\&. 
.PP
Definition at line 116 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Aqua Control from the source code\&.
