.TH "serverA" 3 "Thu Jul 9 2020" "Version 1.0" "Aqua Control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serverA \- WebServer Class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
WebServer Class\&. 

This create a object for handle request response of client
.PP
\fBParameters\fP
.RS 4
\fI80\fP - Web port
.RE
.PP
\fBSee also\fP
.RS 4
other classes
.IP "\(bu" 2
\fBhttpUpdater\fP
.IP "\(bu" 2
\fBRGB\fP 
.PP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Aqua Control from the source code\&.
